##
 # Dependabot auto-merge config for merging patch and minor updates.
 #
 # Based on https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request
 # ______________________________________________________________________________
 #
 # Maintained by brightSPARK Labs.
 # www.brightsparklabs.com
 ##

name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  call-dependabot-auto-merge-workflow:
    uses: cameron-thomson-bsl/github-workflows/.github/workflows/dependabot-auto-merge.yml
    with:
      unit-tests-workflow-ref: cameron-thomson-bsl/asanti/.github/test.yml
      pr_url: ${{ github.event.pull_request.html_url }}
    # Since all of our workflows are called from the same organisation, we can use the `inherit`
    # keyword to pass secrets to the called workflow.
    # See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit
    secrets: inherit
    