##
 # Java workflow to automate testing, dependency patching, and release
 # publishing.
 # ______________________________________________________________________________
 #
 # Maintained by brightSPARK Labs.
 # www.brightsparklabs.com
 ##

name: Java Workflow
on: [push, pull_request]

jobs:
  call-java-workflow:
    uses: brightsparklabs/github-actions/.github/workflows/java.yml@feature/RAD-180-fix-dependabot-auto-merge-for-asanti
    with:
      # Tests for Asanti are run on both Ubuntu and Windows.
      os: '["ubuntu-latest", "windows-latest"]'
    secrets: inherit
    # These permissions are required for Dependabot to merge PRs.
    permissions:
      contents: write
      pull-requests: write
