##
 # Workflow for publishing the `master` branch to Maven Central after unit tests
 # succeed.
 # ______________________________________________________________________________
 #
 # Maintained by brightSPARK Labs.
 # www.brightsparklabs.com
 ##

name: Publish to Maven Central
on:
  # Call workflow on push to the `master` branch.
  push:
    branches:
      - master

jobs:
  call-test-workflow:
    uses: ./.github/workflows/test.yml
  # This workflow contains a single job called "build"
  call-publish-to-maven-central-workflow:
    # Specify that this job should only run if the unit tests job succeeds.
    # See https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequisite-jobs
    needs: call-test-workflow
    uses: brightsparklabs/github-actions/.github/workflows/publish-to-maven-central.yml@feature/RAD-184-create-repo-for-reusable-github-workflows
    with:
      github-ref-name: ${GITHUB_REF_NAME}
    secrets: inherit
