##
 # A workflow for testing for breaking changes.
 #
 # This workflow can be called from workflow jobs in this repo with:
 #  `uses: .github/workflows/test.yml`
 #
 # See https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
 # ______________________________________________________________________________
 #
 # Maintained by brightSPARK Labs.
 # www.brightsparklabs.com
 ##

name: Asanti build with gradle

on:
  # Call workflow on push.
  push:
  # Call workflow when called from other workflows.
  workflow_call:

jobs:
  call-test-gradle-build-workflow:
    uses: cameron-thomson-bsl/github-workflows/.github/workflows/test-gradle-build.yml@develop
