##
 # A workflow for testing for breaking changes.
 #
 # This workflow can be called from workflow jobs in this repo with:
 #  `uses: ./.github/workflows/test.yml`
 #
 # See https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
 # ______________________________________________________________________________
 #
 # Maintained by brightSPARK Labs.
 # www.brightsparklabs.com
 ##

name: Asanti build with Gradle
on:
  # Call workflow on push.
  push:
  # Call workflow when called from other workflows.
  workflow_call:

jobs:
  call-test-gradle-build-workflow:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # Temporarily disabling builds on Windows as the `Fix tag` step fails.
          # The step is a workaround due to `checkout@v3` having a bug.
          # Once the bug is resolved, Windows builds can be re-enabled.
          #- windows-latest
    uses: brightsparklabs/github-actions/.github/workflows/test-gradle-build.yml@feature/RAD-184-create-repo-for-reusable-github-workflows
    with:
      github-ref-name: ${GITHUB_REF_NAME}
      os: ${{ matrix.os }}